# Generated by Django 4.2.4 on 2023-08-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300)),
                ('skills', models.CharField(max_length=200)),
                ('vacant', models.BooleanField(default=False)),
            ],
        ),
    ]
