# Generated by Django 4.2.4 on 2023-08-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='phone',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
