# Generated by Django 4.2.4 on 2023-08-29 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0006_alter_mymodel_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSave',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time_of_upload', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
