# Generated by Django 4.2.4 on 2023-08-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_modelsave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelsave',
            old_name='time_of_upload',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='modelsave',
            name='mymodel_instances',
            field=models.ManyToManyField(related_name='model_saves', to='website.mymodel'),
        ),
        migrations.AlterField(
            model_name='modelsave',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
