# Generated by Django 4.2.4 on 2023-08-29 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0008_rename_time_of_upload_modelsave_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('saved_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.mymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ModelSave',
        ),
    ]
